import Head from 'next/head'; 

export default function Home()
{
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='text-center flex justify-center items-center font-bold text-5xl text-white min-h-screen h-full bg-black'>
        <span className='text-btn-2'>Sleep Well</span>
      </main>
    </>
  );
}
